# This is a basic workflow to help you get started with Actions

name: using-secret

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: show secret
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: echo 패스워드 => $PASSWORD
